version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydatabase
  db:
    image: postgres:15.3
    volumes:
      - /var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase